id: IE97FFA76
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:16:33+00:00'
last_modified: '2022-06-08T16:26:01.087059+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30467
  title: ཡུན་ནན་བོད་ཀྱི་ཤེས་རིག་ཞིབ་འཇུག་ཆེད་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    89CB:
      image_group_id: I1PD36459
      title: ''
      total_pages: 466
      order: 1
      base_file: 89CB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
