id: P010639
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W30467
  title: ཡུན་ནན་བོད་ཀྱི་ཤེས་རིག་ཞིབ་འཇུག་ཆེད་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    49742e88b80747c797b5205cc0738343:
      image_group_id: I1PD36459
      title: ''
      volume_number: 1
      total_pages: 466
      base_file: v001.txt
